name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Check for hardcoded secrets
      run: |
        if grep -r "eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*" . --exclude-dir=.git --exclude-dir=node_modules | grep -v "YOUR_.*_HERE"; then
          echo "❌ Real JWT tokens detected!"
          exit 1
        fi
        echo "✅ No hardcoded secrets found"
    
    - name: Lint check
      run: |
        # Check for common issues
        echo "Running basic lint checks..."
        if grep -r "console\.log" src/ --exclude-dir=node_modules; then
          echo "⚠️ console.log statements found in source code"
        fi